### PR TITLE
Replace 'cash_handled' in DB with 'closed_at'

### LINKED ISSUE #72: Don't require cash handled for the confirm button enabling
I think the confirm button should only be disabled if the start time is past the end time

Other than that, we already have it so if there is no end time, clicking Checkout will automatically set the end time

and otherwise the user will have already set the end time

### PR DESCRIPTION
**Pull request by thecalliopecrashed**
Closes #72

### CODE REVIEW

**Comment by thecalliopecrashed** [comment]
We had been using the `cash_handled` field laterally - not to track the cash tendered, but to mark when an order was closed.

**Comment by MattyAyOh** [comment]
Separate issue, but is this the case?
"I think the confirm button should only be disabled if the start time is past the end time"

**Comment by thecalliopecrashed** [comment]
ah, good catch. Fixing it up.

**Comment by thecalliopecrashed** [comment]
Screen Shot 2019-05-14 at 11 00 15 AM
done. I'll merge this in for today's deploy.

**Pull request merged**
