### PR TITLE
Move frontend code to the root directory

### PR DESCRIPTION
**Pull request by graysonwright**
Netlify doesn't support deploying from a subdirectory.

See https://github.com/assembleapp/slim/pull/20

### CODE REVIEW

**Comment by graysonwright** [comment]
It's like Heroku, for frontend-code only. It gets us those fancy previews for each PR.

Mostly, I'm trying to get the architecture of this app to match up with the architecture of SLIM as much as possible.

**Comment by MattyAyOh** [comment]
noted, thanks ^

**Comment by graysonwright** [comment]
@MattyAyOh would you be cool with moving this repo to the `assembleapp` organization?

If we do that, I can set up Netlify and start getting this deployed again.

**Comment by MattyAyOh** [comment]
the only thing is i'm pretty sure i'm not going to add anything after this
set of features is done-- the app covers a pretty small scope

**Comment by graysonwright** [comment]
Merging so that the master branch works when ya try to set it up.

**Pull request merged**
