### PR TITLE
Add a minimal CircleCI configuration to fix build

### PR DESCRIPTION
**Pull request by thecalliopecrashed**

### CODE REVIEW

**Comment by thecalliopecrashed** [comment]
Alternatively (and preferably), let's turn off the CircleCI integration?

**Comment by MattyAyOh** [comment]
Yeah we can just turn off CI, prolly not worth it right now

**Comment by thecalliopecrashed** [comment]
Alright - that's on you. I don't have admin controls.

**Comment by MattyAyOh** [comment]
OK I think I de-activated it, can you tell?

**Pull request merged**
